name: simple_todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  path_provider: ^2.1.0
  provider: ^6.0.5
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - ./assets/images/

  fonts:
    - family: Cera
      fonts:
        - asset: assets/fonts/CeraPro.ttf
    - family: Bobbers
      fonts:
        - asset: assets/fonts/CeraPro.ttf